config/routes.rb
Rails.application.routes.draw do
  resources :servers do
    get "retry"
  	get "nginx_logs"
    
    resources :logs

    resources :memberships, only: [:index, :create, :destroy], param: :user_id

  	resources :apps do
      get 'rails_logs'
      get 'deploy'
    end
  end

  #get 'webhook/:hook_id' => "webhook#index"
  post 'webhook/:hook_id' => "webhook#index"

  resources :scripts
  devise_for :users

  get 'pricing' => "dashboard#pricing"

  mount StripeEvent::Engine, at: '/stripe/webhook'


  resource :subscription
  resource :card
  resources :charges
  
  namespace :admin do
  	resources :users
  	resources :system_info, only: [:index]
  end

  root 'dashboard#index'

  mount ActionCable.server, at: '/cable'
end

app/models/script.rb
class Script < ApplicationRecord
  belongs_to :user
end

app/controllers/scripts_controller.rb
class ScriptsController < ApplicationController
  before_action :set_script, only: [:show, :edit, :update, :destroy]

  def index
    @q = Script.all.ransack(params[:q])
    @scripts = @q.result.page(params[:page])
  end

  def show
    
  end

  def new
    @script = Script.new
  end

  def edit

  end

  def create
    @script = Script.new(script_params)
    @script.user_id = current_user.id
    if @script.save
      redirect_to @script, notice: 'Script was successfully created.'
    else
      render :new
    end
  end

  def update
    if @script.update(script_params)
      redirect_to @script, notice: 'Script was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @script.destroy
    redirect_to scripts_url, notice: 'Script was successfully destroyed.'
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_script
      @script = Script.find(params[:id])
    end

    def script_params
      params.require(:script).permit(:name, :body, :user_id)
    end
end

app/helpers/scripts_helper.rb
module ScriptsHelper
end

app/views/scripts/_form.html.erb
<%= simple_form_for(@script) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :body, input_html: {class: "col-md-11 codemirror", style: "height: 300px;"} %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, {class: "btn btn-sm btn-primary", data: { keybinding: 'shift+s'}} %>
    <%= link_to 'Back', scripts_path, { class: "btn btn-sm btn-light btn-cancle", data: { keybinding: 'shift+b' }} %>
  </div>
<% end %>

app/views/scripts/edit.html.erb
<div class="mt-2">
	<div class="card-body">
		<h2 class="main-title">Edit Script</h2>
		<%= render 'form', script: @script %>
	</div>
</div>

app/views/scripts/index.html.erb
<div class="main-content-full">
  <div class="top-area">
    <div class="row">
      <div class="col-lg-6">
        <h2 class="top-area-heading">Scripts</h2>
      </div>
      <div class="col-lg-6">
        <div class="nav-controls">
          <%= search_form_for @q, class: "top-area-form" do |f| %>
          <div class="form-group">
            <%= f.search_field :id_eq, class: "form-control", placeholder: "Find by name...", autocomplete: "off", data: { keybinding: '/' } %>
          </div>
          <% end %>
          <%= order_by_dropdown %>
          <%= link_to 'New Script', new_script_path, class: "btn btn-success btn-sm", data: { keybinding: 'shift+n' } %>
        </div>
      </div>
    </div>
  </div>
  <table class="<%= standard_table_class %>">
    <thead>
      <tr>
        <th><%= sort_link(@q, :name) %></th>
        <th><%= sort_link(@q, :created_at) %></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @scripts.each do |script| %>
      <tr">
        <td data-link="<%= script_path(script) %> class="align-middle"><%= script.name %></td>
        <td data-link="<%= script_path(script) %> class="align-middle"><%= script.created_at %></td>
        <td class="align-middle text-right"><%= link_to 'Edit', edit_script_path(script), class: "btn btn-primary btn-sm" %>
        </tr>
        <% end %>
      </tbody>
    </table>
    <%= paginate @scripts,theme: 'twitter-bootstrap-4' %>
  </div>

app/views/scripts/new.html.erb
<div class="mt-2">
	<div class="card-body">
		<h2 class="main-title">New Script</h2>
		<%= render 'form', script: @script %>
	</div>
</div>

app/views/scripts/show.html.erb
<div class="main-content-full">
  <div class="top-area">
    <h2 class="top-area-heading">Script - <%= @script.name %></h2>
  </div>
  
  <div class="code-label">~/.autodeploy/<%= @script.name %></div>
  <pre><%= @script.body %></pre>
  <div class="form-actions">
    <%= link_to 'Back', scripts_path, { class: "btn btn-sm btn-primary", data: { keybinding: 'shift+b' }} %>
    <%= link_to 'Edit', edit_script_path(@script), class: "btn btn-cancle btn-sm mr-2", data: { keybinding: 'shift+e' } %>
  </div>
</div>