config/routes.rb
Rails.application.routes.draw do
  resources :servers do
    get "retry"
  	get "nginx_logs"
    
    resources :logs

    resources :memberships, only: [:index, :create, :destroy], param: :user_id

  	resources :apps do
      get 'rails_logs'
      get 'deploy'
    end
  end

  #get 'webhook/:hook_id' => "webhook#index"
  post 'webhook/:hook_id' => "webhook#index"

  resources :scripts
  devise_for :users

  get 'pricing' => "dashboard#pricing"

  mount StripeEvent::Engine, at: '/stripe/webhook'


  resource :subscription
  resource :card
  resources :charges
  
  namespace :admin do
  	resources :users
  	resources :system_info, only: [:index]
  end

  root 'dashboard#index'

  mount ActionCable.server, at: '/cable'
end

app/views/shared/_admin_aside_menu.html.erb
<ul class="asidemenu nav nav-pills flex-column">
	<li class="nav-item">
		<a class="nav-link <%= active_class('/admin/users') %>" href="/admin/users">User Management</a>
	</li>
	<li class="nav-item">
		<a class="nav-link" href="#">Groups</a>
	</li>
	<li class="nav-item">
		<a class="nav-link" href="#">Roles</a>
	</li>
	<li class="nav-item">
		<a class="nav-link" href="#">Appearance</a>
	</li>
	<li class="nav-item">
		<a class="nav-link <%= active_class('/admin/system_info') %>" href="/admin/system_info">System Information</a>
	</li>
	<div class="dropdown-divider"></div>
	<li class="nav-item">
		<a class="nav-link" href="#">Settings</a>
	</li>
</ul>

app/views/shared/_side-nav.html.erb
<ul class="nav nav-pills flex-column">
	<li class="nav-item">
		<a class="nav-link <%= active_class('/')%>" href="/"><i class="icon material-icons">dashboard</i> Overview</a>
	</li>
	<li class="nav-item">
		<a class="nav-link <%= active_class('/servers')%>" href="/servers"><i class="icon material-icons">cloud_queue</i> Servers</a>
	</li>
	<li class="nav-item">
		<a class="nav-link <%= active_class('/scripts')%>" href="/scripts"><i class="icon material-icons">format_indent_increase</i> Scripts</a>
	</li>
	<li class="nav-item">
		<a class="nav-link <%= active_class('/admin/users')%>" href="/admin/users"><i class="icon material-icons">domain</i> Admin</a>
	</li>
</ul>

app/views/shared/_tab-list.html.erb
<ul class="nav nav-pills mb-3" role="tablist">
  <li class="nav-item">
    <a class="nav-link <%= active_class(server_path(@server)) %>" href="<%= server_path(@server) %>">Status</a>
  </li>
  <li class="nav-item">
    <a class="nav-link <%= active_class(server_apps_path(@server)) %>" href="<%= server_apps_path(@server) %>">Applications</a>
  </li>
  <li class="nav-item">
    <a class="nav-link " href="/servers/1/logs">Logs</a>
  </li>
  <li class="nav-item">
    <a class="nav-link " href="/servers/1/nginx_logs">Nginx</a>
  </li>

  <li class="nav-item">
    <a class="nav-link " href="/servers/1/ssh_keys">SSH Keys</a>
  </li>
  <li class="nav-item">
    <a class="nav-link " href="/servers/1/ruby">Ruby Versions</a>
  </li>

  <li class="nav-item">
    <a class="nav-link " href="/servers/1/postgres">PostgreSQL</a>
  </li>
  <li class="nav-item">
    <a class="nav-link <%= active_class(server_memberships_path(@server)) %>" href="<%= server_memberships_path(@server) %>">Collaborators</a>
  </li>
  <li class="nav-item">
    <a class="nav-link " href="/servers/1/edit">Settings</a>
  </li>
</ul>

app/views/shared/_top-nav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark fixed-top bg-theme bg-dark">
	<a class="navbar-brand" href="/">
		<img src="https://intellecta.services/assets/favicon-eec12ad7c32cc52fe8ef0af497fad15ae8e51877f8593b24e7d900cec0b5df3c.png" alt="" width="30" class="d-inline-block align-top" > Intellecta
	</a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarNav">
			<ul class="navbar-nav ml-auto">
				<li class="nav-item">
					<% unless current_user_subscribed? %>
						<a href="/pricing" class="nav-link" style="color: yellow">Subscribe</a>
					<% end %>
				</li>
				<li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						<%= image_tag avatar_url(current_user), class: "rounded"%> My Account
					</a>
					<div class="dropdown-menu" aria-labelledby="navbarDropdown">
						<a class="dropdown-item" href="/users/edit">Account Settings</a>
						<div class="dropdown-divider"></div>
						<%= link_to('Logout', destroy_user_session_path, method: :delete, class: "dropdown-item") %>
					</div>
				</li>
				<% if user_signed_in? %>
					<li class="nav-item">
						<%= link_to('Logout', destroy_user_session_path, method: :delete, class: "nav-link") %>
					</li>
				<% end %>
			</ul>
		</div>
</nav>