config/routes.rb
Rails.application.routes.draw do
  resources :servers do
    get "retry"
  	get "nginx_logs"
    
    resources :logs

    resources :memberships, only: [:index, :create, :destroy], param: :user_id

  	resources :apps do
      get 'rails_logs'
      get 'deploy'
    end
  end

  #get 'webhook/:hook_id' => "webhook#index"
  post 'webhook/:hook_id' => "webhook#index"

  resources :scripts
  devise_for :users

  get 'pricing' => "dashboard#pricing"

  mount StripeEvent::Engine, at: '/stripe/webhook'


  resource :subscription
  resource :card
  resources :charges
  
  namespace :admin do
  	resources :users
  	resources :system_info, only: [:index]
  end

  root 'dashboard#index'

  mount ActionCable.server, at: '/cable'
end

app/views/apps/_form.html.erb
<%= simple_form_for([@server,@app]) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :repo_url %>
    <%= f.input :branch %>
    <%= f.input :domain %>
    <%= f.input :nginx_ssl %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, {class: "btn btn-sm btn-primary", data: { keybinding: 'shift+s'}} %>
    <%= link_to 'Back', server_apps_path, { class: "btn btn-sm btn-light btn-cancle", data: { keybinding: 'shift+b' }} %>
  </div>
<% end %>

app/views/apps/edit.html.erb
<div class="mt-2">
	<div class="card-body">
		<h2 class="main-title">Edit App</h2>
		<%= render 'form', server: @app %>
	</div>
</div>

app/views/apps/index.html.erb
<div class="main-content-full">
  <div class="top-area">
    <h2 class="top-area-heading">Apps - <%= @server.public_ip %></h2>
  </div>
  
  <%= render "shared/tab-list" %>
  <hr>
  <div class="co-lg-12 pull-right text-right testbtn">
      <a href="<%= new_server_app_path(@server) %>" class="btn btn-success btn-sm">New Application</a>
    </div>
    <br/>
  <table class="<%= standard_table_class %>">
    <thead>
      <tr>
        <th>Name</th>
        <th>Repo</th>
        <th>View</th>
      </tr>
    </thead>

    <tbody>
      <% @apps.each do |app| %>
      <tr>
        <td data-link="<%= server_app_path(@server,app) %>" class="align-middle"><%= app.name %></td>
        <td data-link="<%= server_app_path(@server,app) %>" class="align-middle"><%= app.repo_url %></td>
        <td class="align-middle text-right">
          <%= link_to 'Edit', edit_server_app_path(@server,app), class: "btn btn-primary btn-sm" %>
          <%= link_to 'Destroy', server_app_path(@server,app), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm" %>

        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/apps/new.html.erb
<div class="mt-2">
	<div class="card-body">
		<h2 class="main-title">New App</h2>
		<%= render 'form', server: @app %>
	</div>
</div>

app/views/apps/rails_logs.html.erb
<link rel="stylesheet"
      href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/ocean.min.css">
<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js"></script>
<script>
  $(document).ready(function() {
  $('pre').each(function(i, block) {
    hljs.highlightBlock(block);
  });
});

</script>
<div class="main-content-full">
  <div class="top-area">
    <h2 class="top-area-heading">Server - <%= @app.server.public_ip %></h2>
  </div>
  
  <%= render "shared/tab-list" %>
  <hr>
  
  <div id="start">
    <div class="code-label">Deploy Status..</div>  
    <pre style="overflow: auto; max-height: 400px;" class="accesslog">
      <%
Net::SSH.start(@app.server.public_ip, 'root', :timeout => 10, :number_of_password_prompts => 0) do | ssh |
@logs = ssh.exec!("less /var/log/nginx/error.log")
%>
<%= @logs %>
<% end %>
    </pre>
  </div>
  

</div>

app/views/apps/show.html.erb
<div class="main-content-full">
  <div class="top-area">
    <h2 class="top-area-heading">Apps - <%= @server.public_ip %></h2>
  </div>
  
  <%= render "shared/tab-list" %>
  <hr>
  <div class="row">
    <div class="col-lg-6 text-left">
      <input type="text" class="form-control" value="<%= @app.repo_url %>" disabled="true">
    </div>
    <div class="col-lg-2 text-left">
      <input type="text" class="form-control" value="<%= @app.branch %>" disabled="true">
    </div>
    <div class="col-lg-4 pull-right text-right testbtn">
      <a href="<%= edit_server_app_path(@server,@app)%>" class="btn btn-warning btn-sm">Edit App</a>
      <a href="<%= server_app_deploy_path(@server,@app)%>" class="btn btn-success btn-sm">Deploy Application</a>
    </div>
  </div>
  <br/>
  <div id="start">
    <div class="code-label">~/<%= @app.name %></div>  
    <pre style="overflow: auto; max-height: 400px;" id="message" data-behavior="app-logs" data-record="<%= @app.id %>" data-app-id="<%= @app.id %>"><i class="material-icons icon paragraph-icon">autorenew</i> Waiting for connection...!<br/></pre>
  </div>
  
  <% if @app.env_vars %>
  <br/>
  <h3>Enviroment Variables</h3>
  <table class="table">
    <tr>
      <td>DATABSE_URL</td>
      <td><%= @app.env_vars['DBATABASE_URL'] %></td>
    </tr>
    <tr>
      <td>RAILS_ENV</td>
      <td>production</td>
    </tr>
  </table>
  <br/>
  <% end %>

  <br/>
  <h3>Webhook</h3>
  <br/>
  <div class="code-label">Deploy Webhook</div>
  <pre style="overflow: none"><%= request.base_url%>/webhook/<%= @app.webhook %><br/></pre>
  

  <div class="row">
    <div class="col-lg-12 pull-right text-right testbtn">
      <a href="<%= server_app_rails_logs_path(@server,@app)%>" class="btn btn-primary btn-sm">Application Logs</a>
      <a href="//<%= @app.domain %>" target="_blank" class="btn btn-default btn-sm">Preview App</a>
    </div>
  </div>
  
</div>