config/routes.rb
Rails.application.routes.draw do
  resources :servers do
    get "retry"
  	get "nginx_logs"
    
    resources :logs

    resources :memberships, only: [:index, :create, :destroy], param: :user_id

  	resources :apps do
      get 'rails_logs'
      get 'deploy'
    end
  end

  #get 'webhook/:hook_id' => "webhook#index"
  post 'webhook/:hook_id' => "webhook#index"

  resources :scripts
  devise_for :users

  get 'pricing' => "dashboard#pricing"

  mount StripeEvent::Engine, at: '/stripe/webhook'


  resource :subscription
  resource :card
  resources :charges
  
  namespace :admin do
  	resources :users
  	resources :system_info, only: [:index]
  end

  root 'dashboard#index'

  mount ActionCable.server, at: '/cable'
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :servers
  has_many :memberships
  has_many :charges


  def servers 
    owner       = Server.where(owner: self)
    memberships = Server.joins(:memberships)
      .where(memberships: { user_id: id })

    Server.from("(#{memberships.to_sql} UNION #{owner.to_sql}) AS servers")
  end


  def member?(server)
    Server.joins(:memberships)
      .exists?(memberships: { user_id: id, server_id: server.id })
  end


  def server_admin?(server)
    Server.joins(:memberships)
      .exists?(memberships: { user_id: id, server_id: server.id, role: "admin" })
  end


  def owner?(server)
    server.owner == self
  end

  def subscribed?
		stripe_subscription_id?
	end
	
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController
	before_action :user, except: [:index, :new, :create]
	before_action :set_roles

	def index
    @q = User.ransack(params[:q])
    @users = @q.result.page(params[:page])
	end

  def show
  end

  def new
    @user = User.new
  end


  def edit
  end


  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to admin_users_url, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to edit_admin_user_path(@user), notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to admin_users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  protected

    def user
      @user = User.find(params[:id])
    end

    def default_route
    	[:admin, @user]
  	end

    def set_roles 
    	@roles = Role.all if current_user.has_role? :admin
    end

    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation,:role_ids => [])
    end

end

app/views/admin/users/_form.html.erb
<%= simple_form_for [:admin, @user] do |f| %>
<%= f.error_notification %>

  <%= f.input :email, required: true %>  
  <%= f.input :password, required: true %>
  <%= f.input :password_confirmation, required: true %>
    
  <div class="form-actions">
      <%= f.button :submit, {class: "btn btn-sm btn-primary"} %>
    <%= link_to 'Back', admin_users_path, { class: "btn btn-sm btn-light btn-cancle"} %>
  </div>
<% end %>

app/views/admin/users/edit.html.erb
<div class="mt-2">
	<div class="card-body">
		<h2 class="main-title">Edit User</h2>
		<%= render 'form' %>
	</div>
</div>

app/views/admin/users/index.html.erb
<div class="row">
  <%= content_tag :div, nil, class: admin_aside_left_class.split do %>
  <%= render "shared/admin_aside_menu" %>
  <% end %>
  <%= content_tag :div, nil, class: admin_aside_right_class.split do %>
  <div class=" content-with-asidemenu">
    <div class="card-body">
      <h3 class="card-title align-middle">
        Users
      </h3>
      <div class="card-text">
        <p>List of all the users present in database</p>

        <div class="card bg-light border-light mb-3 search_fields_box <%= filter_params_present%>">
          <div class="card-body">
            <h4 class="card-title">Search Filters</h4>
              <%= search_form_for [:admin, @q], class: "form-inline" do |f| %>
                <div class="form-group">
                  <%= f.search_field :id_eq, class: "form-control", placeholder: "ID" %>
                </div>
                <div class="form-group mx-sm-3">
                  <%= f.search_field :email_cont, class: "form-control", placeholder: "Email" %>
                </div>
                <button type="submit" class="btn btn-success btn-sm mx-sm-1">Search</button>
                <button type="button" id="reset" method="get" data-path="<%=request.path %>" class="btn btn-sm btn-danger btn-fill pull-right">Clear</button>
              <% end %>
          </div>
        </div>

        <p>
          <%= filter_button %>
          <%= link_to 'New User', new_admin_user_path, class: "btn btn-success btn-sm " %>    
        </p>
        <table class="<%= standard_table_class %>">
          <thead>
            <tr>
              <th><%= sort_link(@q, :id) %></th>
              <th><%= sort_link(@q, :email) %></th>
              <th>Roles</th>
              <th><%= sort_link(@q, :created_at) %></th>
              <th></th>
            </tr>
          </thead>

          <tbody>
            <% @users.each do |user| %>
            <tr>
              <td class="align-middle"><%= user.id %></td>
              <td class="align-middle"><%= user.email %></td>
              <td class="align-middle"><%= user.roles.map{ |role| "<span class='badge badge-pill badge-success'>#{role.name.capitalize}</span>"}.join(',').html_safe %></td>
              <td class="align-middle"><%= formatted_date(user.created_at) %></td>
              <td class="align-middle text-right">
                <%= link_to 'Show', admin_user_path(user), class: "btn btn-info btn-sm" %>
                <%= link_to 'Edit', edit_admin_user_path(user), class: "btn btn-primary btn-sm" %>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
        <%= paginate @users,theme: 'twitter-bootstrap-4' %>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/admin/users/new.html.erb
<div class="mt-2">
	<div class="card-body">
		<h2 class="main-title">New User</h2>
		<%= render 'form' %>
	</div>
</div>